server:
  port: 7888
spring:
  application:
    name: producer
  cloud:
    stream:
      kafka:
        binder:
          #Kafka的消息中间件服务器
          brokers: localhost:9092
          #Zookeeper的节点，如果集群，后面加,号分隔
          zk-nodes: localhost:2181
          #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          autoCreateTopics: true
          autoAddPartitions: true
          minPartitionCount: 1
      bindings:
        alarmOutput:
          #消息发往的目的地
          destination: asyncMsg-topic
          producer:
            partitionCount: 1
        alarmInput:
          #消息发往的目的地,topic
          destination: asyncMsg-topic
          group: phsms-group
          consumer:
            concurrency: 1
        defaultOutput:
          #消息发往的目的地
          destination: defaultMsg-topic
          producer:
            #分区数
            partitionCount: 2
        defaultInput:
          #消息发往的目的地,topic
          destination: defaultMsg-topic
          #消费者组名称
          group: phsms-group
          consumer:
            #入站消费者的并发性，消费者个数
            concurrency: 2
  kafka:
    consumer:
      #一次poll调用最多返回记录数
      maxPollRecords: 10
      enableAutoCommit: true
      autoCommitInterval: 2000